config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists do
    resources :movies, only: :create
  end
  resources :movies, only: :destroy do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :photo
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, comment: "This movie is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def article_params
  params.require(:article).permit(:title, :body, :photo)
end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @movie = Movie.find(params[:movie_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @movie = Movie.find(params[:movie_id])
    @bookmark.movie = @movie

    if @bookmark.save
      redirect_to list_path(@movie.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  # GET /lists
  def index
    @lists = List.all
  end

  # Gets /lists/1
  def show
    @list = List.find(params[:id])
  end

  # GET /Lists/new
  def new
    @list = List.new
  end

  # POST /lists
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: "list successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @movie = Movie.new(movie_params)
    @movie.list = @list

    if @movie.save
      redirect_to list.path(@list)
    else
      @movies = @list.movies
      render "lists/show", status: :unprocessable_entity
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(article, html: { multipart: true }) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Publier" %>
<% end %>

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>

<ul>
<% @bookmarks.each do |bookmark| %>
  <li><%= link_to bookmark.name, bookmark_path(bookmark) %></li>
<% end %>
</ul>

<%= link_to "+ Add a new bookmark", list_path %>

app/views/bookmarks/new.html.erb
<h1>Add a Bookmark ...</h1>

<div class="container w-25">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.button :submit, list_bookmarks_path, class: "btn btn-primary" %>
  <% end %>
<br>
<%= link_to "back", list_path, class: "btn btn-warning" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Films Lists</h1>

<ul>
<% @lists.each do |list| %>
  <li><%= link_to list.name, list_path(list) %></li>
<% end %>
</ul>

<%= link_to "+ Add a new list", new_list_path %>

app/views/lists/new.html.erb
<!--  -->
<h1>New List ...</h1>

<div class="container w-25">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.submit "Submit list", class: "btn btn-primary" %>
  <% end %>
<br>
<%= link_to "back", lists_path, class: "btn btn-warning" %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

<%= link_to "back", lists_path, class: "btn btn-warning" %>

<!-- <%= cl_image_tag @article.photo.key, height: 300, width: 400, crop: :fill %>

<% if @article.photo.attached? %>
  <%= image_tag cl_image_path(@article.photo.key, height: 300, crop: :fill) %>
<% end %> -->